
services:
  db:
    image: mysql:8.0
    container_name: mysql_db_v2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 11080310       
      MYSQL_DATABASE: blog 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_app_v2
    command: gunicorn Blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True

volumes:
  mysql_data:
